# Generated by Django 4.0.6 on 2022-07-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_author_date_of_death'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='test', upload_to='uploads'),
            preserve_default=False,
        ),
    ]
